name: Syntax Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup arduino-cli
        uses: arduino/setup-arduino-cli@v2
        with:
          version: '1.x'

      - name: Install ESP32 core
        run: |
          arduino-cli config init
          arduino-cli core update-index \
            --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 \
            --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Syntax check
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32s3 \
            --only-compilation-database \
            Thermal-Printer
